### ISSUE TITLE
Time offset

### ISSUE THREAD

**Issue by moshed** [yfrans/node-red-contrib-hebcal#1]
Is it possible to set a time offset so that user can test their flows before actually deploying to regular usage without having to rely on the fact the we configured everything properly.

**Comment by yfrans** [comment]
Use "inject" node.

**Comment by moshed** [comment]
@yfrans tagging you since him not sure you get notified on closed topics.

Maybe I am missing something. What I want to accomplish is a "test" of my flow before I deploy it using this node since I cant check on a day of issur melacha. Using the inject node just tells me if _now_ is an issur melacha but I cant check if everything will work when it is an issue melacha. 

a time offset would solve this since I can set it +/- X hours and see how it would trigger if it was issur melacha
